/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaTorch */

#ifndef _Included_JavaTorch
#define _Included_JavaTorch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaTorch
 * Method:    inference
 * Signature: (Ljava/lang/String;LDummyLightCurve;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_JavaTorch_inference
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
